// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _CCLabel_preProcess_HH_
#define _CCLabel_preProcess_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct CCLabel_preProcess : public sc_module {
    // Port declarations 15
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<32> > Image_r_Addr_A;
    sc_out< sc_logic > Image_r_EN_A;
    sc_out< sc_lv<4> > Image_r_WEN_A;
    sc_out< sc_lv<32> > Image_r_Din_A;
    sc_in< sc_lv<32> > Image_r_Dout_A;
    sc_out< sc_lv<6> > lbImage_address0;
    sc_out< sc_logic > lbImage_ce0;
    sc_out< sc_logic > lbImage_we0;
    sc_out< sc_lv<32> > lbImage_d0;


    // Module declarations
    CCLabel_preProcess(sc_module_name name);
    SC_HAS_PROCESS(CCLabel_preProcess);

    ~CCLabel_preProcess();

    sc_trace_file* mVcdFile;

    sc_signal< sc_lv<10> > ap_CS_fsm;
    sc_signal< sc_logic > ap_sig_cseq_ST_st1_fsm_0;
    sc_signal< bool > ap_sig_bdd_28;
    sc_signal< sc_lv<4> > i_reg_198;
    sc_signal< sc_lv<1> > exitcond1_fu_225_p2;
    sc_signal< sc_lv<1> > exitcond1_reg_324;
    sc_signal< sc_logic > ap_sig_cseq_ST_pp0_stg0_fsm_1;
    sc_signal< bool > ap_sig_bdd_56;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it0;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it1;
    sc_signal< sc_lv<4> > i_1_fu_231_p2;
    sc_signal< sc_lv<4> > i_1_reg_328;
    sc_signal< sc_lv<6> > tmp_fu_241_p3;
    sc_signal< sc_lv<6> > tmp_reg_333;
    sc_signal< sc_lv<64> > tmp_3_fu_249_p1;
    sc_signal< sc_lv<64> > tmp_3_reg_344;
    sc_signal< sc_lv<64> > tmp_3_1_fu_259_p1;
    sc_signal< sc_lv<64> > tmp_3_1_reg_354;
    sc_signal< sc_logic > ap_sig_cseq_ST_pp0_stg1_fsm_2;
    sc_signal< bool > ap_sig_bdd_81;
    sc_signal< sc_lv<64> > tmp_3_2_fu_269_p1;
    sc_signal< sc_lv<64> > tmp_3_2_reg_364;
    sc_signal< sc_logic > ap_sig_cseq_ST_pp0_stg2_fsm_3;
    sc_signal< bool > ap_sig_bdd_94;
    sc_signal< sc_lv<64> > tmp_3_3_fu_279_p1;
    sc_signal< sc_lv<64> > tmp_3_3_reg_374;
    sc_signal< sc_logic > ap_sig_cseq_ST_pp0_stg3_fsm_4;
    sc_signal< bool > ap_sig_bdd_106;
    sc_signal< sc_lv<64> > tmp_3_4_fu_289_p1;
    sc_signal< sc_lv<64> > tmp_3_4_reg_384;
    sc_signal< sc_logic > ap_sig_cseq_ST_pp0_stg4_fsm_5;
    sc_signal< bool > ap_sig_bdd_118;
    sc_signal< sc_lv<64> > tmp_3_5_fu_299_p1;
    sc_signal< sc_lv<64> > tmp_3_5_reg_394;
    sc_signal< sc_logic > ap_sig_cseq_ST_pp0_stg5_fsm_6;
    sc_signal< bool > ap_sig_bdd_130;
    sc_signal< sc_lv<64> > tmp_3_6_fu_309_p1;
    sc_signal< sc_lv<64> > tmp_3_6_reg_404;
    sc_signal< sc_logic > ap_sig_cseq_ST_pp0_stg6_fsm_7;
    sc_signal< bool > ap_sig_bdd_142;
    sc_signal< sc_lv<64> > tmp_3_7_fu_319_p1;
    sc_signal< sc_lv<64> > tmp_3_7_reg_414;
    sc_signal< sc_logic > ap_sig_cseq_ST_pp0_stg7_fsm_8;
    sc_signal< bool > ap_sig_bdd_154;
    sc_signal< sc_lv<4> > i_phi_fu_202_p4;
    sc_signal< sc_lv<32> > Image_r_Addr_A_orig;
    sc_signal< sc_lv<1> > grp_fu_210_p2;
    sc_signal< sc_lv<3> > tmp_33_fu_237_p1;
    sc_signal< sc_lv<6> > tmp_2_s_fu_254_p2;
    sc_signal< sc_lv<6> > tmp_2_1_fu_264_p2;
    sc_signal< sc_lv<6> > tmp_2_2_fu_274_p2;
    sc_signal< sc_lv<6> > tmp_2_3_fu_284_p2;
    sc_signal< sc_lv<6> > tmp_2_4_fu_294_p2;
    sc_signal< sc_lv<6> > tmp_2_5_fu_304_p2;
    sc_signal< sc_lv<6> > tmp_2_6_fu_314_p2;
    sc_signal< sc_logic > ap_sig_cseq_ST_st11_fsm_9;
    sc_signal< bool > ap_sig_bdd_298;
    sc_signal< sc_lv<10> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<10> ap_ST_st1_fsm_0;
    static const sc_lv<10> ap_ST_pp0_stg0_fsm_1;
    static const sc_lv<10> ap_ST_pp0_stg1_fsm_2;
    static const sc_lv<10> ap_ST_pp0_stg2_fsm_3;
    static const sc_lv<10> ap_ST_pp0_stg3_fsm_4;
    static const sc_lv<10> ap_ST_pp0_stg4_fsm_5;
    static const sc_lv<10> ap_ST_pp0_stg5_fsm_6;
    static const sc_lv<10> ap_ST_pp0_stg6_fsm_7;
    static const sc_lv<10> ap_ST_pp0_stg7_fsm_8;
    static const sc_lv<10> ap_ST_st11_fsm_9;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<32> ap_const_lv32_46;
    static const sc_lv<4> ap_const_lv4_8;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<6> ap_const_lv6_1;
    static const sc_lv<6> ap_const_lv6_2;
    static const sc_lv<6> ap_const_lv6_3;
    static const sc_lv<6> ap_const_lv6_4;
    static const sc_lv<6> ap_const_lv6_5;
    static const sc_lv<6> ap_const_lv6_6;
    static const sc_lv<6> ap_const_lv6_7;
    static const sc_lv<32> ap_const_lv32_9;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_Image_r_Addr_A();
    void thread_Image_r_Addr_A_orig();
    void thread_Image_r_Din_A();
    void thread_Image_r_EN_A();
    void thread_Image_r_WEN_A();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_sig_bdd_106();
    void thread_ap_sig_bdd_118();
    void thread_ap_sig_bdd_130();
    void thread_ap_sig_bdd_142();
    void thread_ap_sig_bdd_154();
    void thread_ap_sig_bdd_28();
    void thread_ap_sig_bdd_298();
    void thread_ap_sig_bdd_56();
    void thread_ap_sig_bdd_81();
    void thread_ap_sig_bdd_94();
    void thread_ap_sig_cseq_ST_pp0_stg0_fsm_1();
    void thread_ap_sig_cseq_ST_pp0_stg1_fsm_2();
    void thread_ap_sig_cseq_ST_pp0_stg2_fsm_3();
    void thread_ap_sig_cseq_ST_pp0_stg3_fsm_4();
    void thread_ap_sig_cseq_ST_pp0_stg4_fsm_5();
    void thread_ap_sig_cseq_ST_pp0_stg5_fsm_6();
    void thread_ap_sig_cseq_ST_pp0_stg6_fsm_7();
    void thread_ap_sig_cseq_ST_pp0_stg7_fsm_8();
    void thread_ap_sig_cseq_ST_st11_fsm_9();
    void thread_ap_sig_cseq_ST_st1_fsm_0();
    void thread_exitcond1_fu_225_p2();
    void thread_grp_fu_210_p2();
    void thread_i_1_fu_231_p2();
    void thread_i_phi_fu_202_p4();
    void thread_lbImage_address0();
    void thread_lbImage_ce0();
    void thread_lbImage_d0();
    void thread_lbImage_we0();
    void thread_tmp_2_1_fu_264_p2();
    void thread_tmp_2_2_fu_274_p2();
    void thread_tmp_2_3_fu_284_p2();
    void thread_tmp_2_4_fu_294_p2();
    void thread_tmp_2_5_fu_304_p2();
    void thread_tmp_2_6_fu_314_p2();
    void thread_tmp_2_s_fu_254_p2();
    void thread_tmp_33_fu_237_p1();
    void thread_tmp_3_1_fu_259_p1();
    void thread_tmp_3_2_fu_269_p1();
    void thread_tmp_3_3_fu_279_p1();
    void thread_tmp_3_4_fu_289_p1();
    void thread_tmp_3_5_fu_299_p1();
    void thread_tmp_3_6_fu_309_p1();
    void thread_tmp_3_7_fu_319_p1();
    void thread_tmp_3_fu_249_p1();
    void thread_tmp_fu_241_p3();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
