webtalk_init -webtalk_dir D:\\zedboard_projects\\CCLabelling_bigDataSet\\CCLabelling_bigDataSet.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Mar 20 17:50:42 2017" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211074886_1777510251_0_724" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "d32sh76a9ube835j83q666njtj" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2014.4_61" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "61" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3392 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1489979558880" -context "sdk\\\\application/1489979558880"
webtalk_add_data -client sdk -key hwid -value "1489657972204" -context "sdk\\\\application/1489979558880"
webtalk_add_data -client sdk -key bspid -value "1489658062424" -context "sdk\\\\application/1489979558880"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1489979558880"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1489979558880"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1489979558880"
webtalk_transmit -clientid 99195517 -regid "211074886_1777510251_0_724" -xml D:\\zedboard_projects\\CCLabelling_bigDataSet\\CCLabelling_bigDataSet.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html D:\\zedboard_projects\\CCLabelling_bigDataSet\\CCLabelling_bigDataSet.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm D:\\zedboard_projects\\CCLabelling_bigDataSet\\CCLabelling_bigDataSet.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
