
SOURCE_MAIN=thesis

clean:
	rm -rf \
		$(SOURCE_MAIN).aux \
		$(SOURCE_MAIN).bbl \
		$(SOURCE_MAIN).blg \
		$(SOURCE_MAIN).log \
		$(SOURCE_MAIN).lot \
		$(SOURCE_MAIN).toc \
		$(SOURCE_MAIN).lof \
		$(SOURCE_MAIN).synctex.gz \
		$(SOURCE_MAIN).dvi \
		$(SOURCE_MAIN).fdb_latexmk \
		$(SOURCE_MAIN).fls
	rm -rf .//1_foreword//*.aux
	rm -rf .//2_chapters//*.aux
	rm -rf .//3_bibliography//*.aux
	rm -rf .//4_appendix//*.aux

